# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CreateDataset.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSplitter, QWidget)
import assets_rc
import assets_rc

class Ui_CreateDataset(object):
    def setupUi(self, CreateDataset):
        if not CreateDataset.objectName():
            CreateDataset.setObjectName(u"CreateDataset")
        CreateDataset.resize(1017, 632)
        self.gridLayout_3 = QGridLayout(CreateDataset)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.splitter_6 = QSplitter(CreateDataset)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Horizontal)
        self.groupBox_3 = QGroupBox(self.splitter_6)
        self.groupBox_3.setObjectName(u"groupBox_3")
        font = QFont()
        font.setFamilies([u"\u9ed1\u4f53"])
        font.setPointSize(13)
        self.groupBox_3.setFont(font)
        self.gridLayout_2 = QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.splitter_3 = QSplitter(self.groupBox_3)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setFrameShadow(QFrame.Plain)
        self.splitter_3.setOrientation(Qt.Vertical)
        self.splitter_3.setHandleWidth(0)
        self.splitter_3.setChildrenCollapsible(True)
        self.OpenCamera = QPushButton(self.splitter_3)
        self.OpenCamera.setObjectName(u"OpenCamera")
        self.OpenCamera.setEnabled(True)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenCamera.sizePolicy().hasHeightForWidth())
        self.OpenCamera.setSizePolicy(sizePolicy)
        self.OpenCamera.setSizeIncrement(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"\u9ed1\u4f53"])
        font1.setPointSize(20)
        font1.setBold(False)
        font1.setItalic(False)
        self.OpenCamera.setFont(font1)
        self.OpenCamera.setAutoFillBackground(False)
        self.OpenCamera.setStyleSheet(u"padding:5;\n"
"margin:3")
        self.OpenCamera.setIconSize(QSize(16, 24))
        self.OpenCamera.setFlat(False)
        self.splitter_3.addWidget(self.OpenCamera)
        self.VideoCapture = QLabel(self.splitter_3)
        self.VideoCapture.setObjectName(u"VideoCapture")
        sizePolicy1 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.VideoCapture.sizePolicy().hasHeightForWidth())
        self.VideoCapture.setSizePolicy(sizePolicy1)
        self.VideoCapture.setPixmap(QPixmap(u":/emoji/Pages/assets/emoji/1.png"))
        self.VideoCapture.setScaledContents(True)
        self.splitter_3.addWidget(self.VideoCapture)

        self.gridLayout_2.addWidget(self.splitter_3, 0, 0, 1, 1)

        self.splitter_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QGroupBox(self.splitter_6)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setFont(font)
        self.gridLayout = QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(u"gridLayout")
        self.splitter_4 = QSplitter(self.groupBox_4)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Vertical)
        self.label_9 = QLabel(self.splitter_4)
        self.label_9.setObjectName(u"label_9")
        font2 = QFont()
        font2.setFamilies([u"\u9ed1\u4f53"])
        font2.setPointSize(12)
        self.label_9.setFont(font2)
        self.label_9.setStyleSheet(u"margin:5")
        self.splitter_4.addWidget(self.label_9)
        self.ShowFaceImage = QLabel(self.splitter_4)
        self.ShowFaceImage.setObjectName(u"ShowFaceImage")
        self.ShowFaceImage.setPixmap(QPixmap(u":/emoji/Pages/assets/emoji/2.png"))
        self.ShowFaceImage.setScaledContents(True)
        self.splitter_4.addWidget(self.ShowFaceImage)
        self.label_10 = QLabel(self.splitter_4)
        self.label_10.setObjectName(u"label_10")
        font3 = QFont()
        font3.setFamilies([u"\u9ed1\u4f53"])
        font3.setPointSize(16)
        self.label_10.setFont(font3)
        self.splitter_4.addWidget(self.label_10)
        self.splitter = QSplitter(self.splitter_4)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.DatasetLabel = QLineEdit(self.splitter)
        self.DatasetLabel.setObjectName(u"DatasetLabel")
        font4 = QFont()
        font4.setFamilies([u"Times New Roman"])
        font4.setPointSize(16)
        self.DatasetLabel.setFont(font4)
        self.splitter.addWidget(self.DatasetLabel)
        self.InputLabel = QPushButton(self.splitter)
        self.InputLabel.setObjectName(u"InputLabel")
        self.InputLabel.setEnabled(True)
        self.InputLabel.setFont(font3)
        self.splitter.addWidget(self.InputLabel)
        self.splitter_4.addWidget(self.splitter)
        self.widget = QWidget(self.splitter_4)
        self.widget.setObjectName(u"widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.ImageCount_2 = QLabel(self.widget)
        self.ImageCount_2.setObjectName(u"ImageCount_2")
        font5 = QFont()
        font5.setFamilies([u"\u9ed1\u4f53"])
        font5.setPointSize(20)
        self.ImageCount_2.setFont(font5)
        self.ImageCount_2.setStyleSheet(u"")
        self.ImageCount_2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.ImageCount_2)

        self.ImageCount = QLabel(self.widget)
        self.ImageCount.setObjectName(u"ImageCount")
        self.ImageCount.setFont(font5)
        self.ImageCount.setStyleSheet(u"")
        self.ImageCount.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.ImageCount)

        self.ImageCount_3 = QLabel(self.widget)
        self.ImageCount_3.setObjectName(u"ImageCount_3")
        self.ImageCount_3.setFont(font5)
        self.ImageCount_3.setStyleSheet(u"")
        self.ImageCount_3.setAlignment(Qt.AlignCenter)

        self.horizontalLayout.addWidget(self.ImageCount_3)

        self.splitter_4.addWidget(self.widget)
        self.splitter_2 = QSplitter(self.splitter_4)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.Start = QPushButton(self.splitter_2)
        self.Start.setObjectName(u"Start")
        self.Start.setEnabled(True)
        palette = QPalette()
        brush = QBrush(QColor(0, 255, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.Start.setPalette(palette)
        self.Start.setFont(font3)
        self.Start.setStyleSheet(u"padding:5")
        self.Start.setIconSize(QSize(16, 16))
        self.Start.setCheckable(False)
        self.Start.setAutoExclusive(False)
        self.splitter_2.addWidget(self.Start)
        self.Pause = QPushButton(self.splitter_2)
        self.Pause.setObjectName(u"Pause")
        self.Pause.setEnabled(False)
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Button, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.Pause.setPalette(palette1)
        self.Pause.setFont(font3)
        self.Pause.setStyleSheet(u"padding:5")
        self.Pause.setIconSize(QSize(16, 16))
        self.Pause.setCheckable(False)
        self.Pause.setAutoExclusive(False)
        self.splitter_2.addWidget(self.Pause)
        self.Continue = QPushButton(self.splitter_2)
        self.Continue.setObjectName(u"Continue")
        self.Continue.setEnabled(False)
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.Continue.setPalette(palette2)
        self.Continue.setFont(font3)
        self.Continue.setStyleSheet(u"padding:5")
        self.Continue.setIconSize(QSize(16, 16))
        self.Continue.setCheckable(False)
        self.Continue.setAutoExclusive(False)
        self.splitter_2.addWidget(self.Continue)
        self.splitter_4.addWidget(self.splitter_2)
        self.NextLabel = QPushButton(self.splitter_4)
        self.NextLabel.setObjectName(u"NextLabel")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.Button, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.NextLabel.setPalette(palette3)
        self.NextLabel.setFont(font3)
        self.NextLabel.setStyleSheet(u"padding:5")
        self.NextLabel.setIconSize(QSize(16, 16))
        self.NextLabel.setCheckable(False)
        self.NextLabel.setAutoExclusive(False)
        self.splitter_4.addWidget(self.NextLabel)
        self.Finish = QPushButton(self.splitter_4)
        self.Finish.setObjectName(u"Finish")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Button, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush)
        self.Finish.setPalette(palette4)
        self.Finish.setFont(font5)
        self.Finish.setStyleSheet(u"padding:5")
        self.Finish.setIconSize(QSize(16, 16))
        self.Finish.setCheckable(False)
        self.Finish.setAutoExclusive(False)
        self.splitter_4.addWidget(self.Finish)

        self.gridLayout.addWidget(self.splitter_4, 0, 0, 1, 1)

        self.splitter_6.addWidget(self.groupBox_4)

        self.gridLayout_3.addWidget(self.splitter_6, 0, 0, 1, 1)


        self.retranslateUi(CreateDataset)

        QMetaObject.connectSlotsByName(CreateDataset)
    # setupUi

    def retranslateUi(self, CreateDataset):
        CreateDataset.setWindowTitle(QCoreApplication.translate("CreateDataset", u"\u5f55\u5236\u6570\u636e\u96c6", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("CreateDataset", u"\u5b9e\u65f6\u6444\u50cf\u753b\u9762", None))
        self.OpenCamera.setText(QCoreApplication.translate("CreateDataset", u"\u6253\u5f00\u6444\u50cf\u5934", None))
        self.VideoCapture.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("CreateDataset", u"\u5f55\u5165\u6570\u636e\u96c6", None))
        self.label_9.setText(QCoreApplication.translate("CreateDataset", u"\u622a\u53d6\u9762\u90e8\u533a\u57df", None))
        self.ShowFaceImage.setText("")
        self.label_10.setText(QCoreApplication.translate("CreateDataset", u"\u5f53\u524d\u6807\u7b7e", None))
        self.DatasetLabel.setText(QCoreApplication.translate("CreateDataset", u"\u8bf7\u8f93\u5165\u6807\u7b7e", None))
        self.InputLabel.setText(QCoreApplication.translate("CreateDataset", u"\u786e\u5b9a", None))
        self.ImageCount_2.setText(QCoreApplication.translate("CreateDataset", u"\u7b2c", None))
        self.ImageCount.setText(QCoreApplication.translate("CreateDataset", u"0", None))
        self.ImageCount_3.setText(QCoreApplication.translate("CreateDataset", u"\u5f20", None))
        self.Start.setText(QCoreApplication.translate("CreateDataset", u"\u5f00\u59cb\u5f55\u5165", None))
        self.Pause.setText(QCoreApplication.translate("CreateDataset", u"\u6682\u505c\u5f55\u5165", None))
        self.Continue.setText(QCoreApplication.translate("CreateDataset", u"\u7ee7\u7eed\u5f55\u5165", None))
        self.NextLabel.setText(QCoreApplication.translate("CreateDataset", u"\u4e0b\u4e00\u4e2a\u6807\u7b7e", None))
        self.Finish.setText(QCoreApplication.translate("CreateDataset", u"\u5b8c\u6210", None))
    # retranslateUi

